#  Each of the sub-playbooks already expect to iterate over all nodePools in all clusters, leave it that way for now
#  TODO: move all iteration over nodePools/clusters to this task and out of node-specific tasks
- include: nodepool-setup.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: (a_cluster.providerConfig.type == 'cloudinit') and (a_cluster.kubeAuth.authn.oidc is defined)
