---
- name: rename cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Gather inventory of all cluster nodes
  ec2_remote_facts:
    region: "{{ cluster.providerConfig.region }}"
    aws_access_key: "{{ cluster.providerConfig.authentication.accessKey or omit }}"
    aws_secret_key: "{{ cluster.providerConfig.authentication.accessSecret or omit }}"
    profile: "{{ cluster.providerConfig.authentication.credentialsProfile or omit }}"
    filters:
      "tag:k2-nodepool": "{{ item.name }}"
      "tag:Name": "{{ cluster.name }}_{{ item.name }}*"
  with_items: "{{ cluster.nodePools }}"
  register: ec2_results

- name: Generate ssh inventory
  template: src=ssh_config.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/ssh_config"
